### ISSUE TITLE
Weather Symbols in KF 5.16

### ISSUE THREAD

**Issue by robby81** [kotelnik/plasma-applet-weather-widget#10]
I see a kind of a regression on my latest openSUSE TW using KF 5.16. The weather symbols are not shown correctly when having the plasmoid in the panel and opening the view. I do not see clouds etc but "fl", "|", empty field and others.
I can remember a time frame where this already occurs in the past.

Plasmoid build from todays git source.

**Comment by robby81** [comment]
you can ignore this, it had to do with some font setting a played around with

**Comment by kotelnik** [comment]
Good to hear you resolved it :)
