### ISSUE TITLE
Translation GUI

### ISSUE THREAD

**Issue by FadeMind** [kotelnik/plasma-applet-weather-widget#12]
@kotelnik I want make polish language translation for weather widget. It is possible?

**Comment by kotelnik** [comment]
Hi! Thanks a lot. Not yet, sorry, but it will definitely be possible. I'll work on it soon.

**Comment by kotelnik** [comment]
Hello again. I've finally prepared the localization support. I'm quite new in this so feel free to ask and criticize and I'll try to make things right. Be sure to write your name to the translation file :-).

File for polish translations: https://github.com/kotelnik/plasma-applet-weather-widget/blob/master/translations/plasma_applet_org.kde.weatherWidget_pl.po

**Comment by FadeMind** [comment]
@kotelnik https://github.com/kotelnik/plasma-applet-weather-widget/pull/15

**Comment by kotelnik** [comment]
Again, thanks a lot!

And just for your information: based on an advice from another translator I've moved *.po files into "po" subfolder.
