### ISSUE TITLE
Don't display "Next Location" when there's only one

### ISSUE THREAD

**Issue by KAMiKAZOW** [kotelnik/plasma-applet-weather-widget#13]
If only one location is set in the preferences, don't display the "Next Location" link.

**Comment by kotelnik** [comment]
Thanks! You're right, I'll repair it.

**Comment by kotelnik** [comment]
Fixed with latest commit https://github.com/kotelnik/plasma-applet-weather-widget/commit/6df73904f7154f3f31123e539d471670f929d752
I'll do a new release soon. Please reopen if not working.
