### ISSUE TITLE
missing translation strings

### ISSUE THREAD

**Issue by FadeMind** [kotelnik/plasma-applet-weather-widget#16]
@kotelnik 
Description from submit URL yr.no window have not translated strings.

Second issue: General tab icon is missing at all but IDK why.
![screenshot_20160327_132832](https://cloud.githubusercontent.com/assets/9846948/14065173/d30a5f36-f41f-11e5-9e7a-6fcb0e91b170.png)

NOTE: for OWM translation string is FINE:
![screenshot_20160327_132926](https://cloud.githubusercontent.com/assets/9846948/14065175/f227ed5c-f41f-11e5-8e17-388f3744f54d.png)

**Comment by kotelnik** [comment]
I missed this one, thanks! I'll fix it right away.
