### ISSUE TITLE
Wind speed in km/h

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-weather-widget#18]
Nice applet!

I would like to suggest to have wind speed in km/h as it is a useful reference for some people, and would be nice to have it as an option.

Thanks

**Comment by FadeMind** [comment]
@kotelnik @kupiqu :+1:

**Comment by kotelnik** [comment]
Thanks for feedback and suggestion! Done in commit https://github.com/kotelnik/plasma-applet-weather-widget/commit/d242cfdfe8696313e733a39b01830fb2e90a6714
