### ISSUE TITLE
Meterogram doesn't display nicely with non-default scaling/font selection

### ISSUE THREAD

**Issue by tz-m** [kotelnik/plasma-applet-weather-widget#25]
On my 3200x1800 display, the meterogram is too tiny to read, and the text is jumbled. It would be great if the system settings related to hidpi screens could be taken into account. e.g. display scaling, forced font dpi. 

Cheers for the widget though!

![snapshot1](https://cloud.githubusercontent.com/assets/17085857/14102395/307313fc-f592-11e5-8d7b-46d94478c2cd.png)

**Comment by kotelnik** [comment]
Hi! Thanks for the report!

You are right, hidpi is not taken into account. I'll try to fix that. But I think I've already fixed the font size disproportions. Can you please check that you are running 1.6.6 version of the plasmoid? (Look at Settings -> General: top right corner)
![screenshot_20160330_070148](https://cloud.githubusercontent.com/assets/1174734/14132366/64366be0-f645-11e5-8a85-cacd7fe402f7.png)

**Comment by kotelnik** [comment]
Nevermind, I can simulate the issue, too. Sorry for the noise :). I'll fix it.

**Comment by tz-m** [comment]
I've managed to make some changes where I multiplied many of the hard-coded pixel values by the relevant quantity...
units.devicePixelScale
or
theme.defaultFont.pixelSize

Tested on my 13" screen, and it works. From this:
![snapshot2](https://cloud.githubusercontent.com/assets/17085857/14144963/e7182c44-f689-11e5-81ca-0c1bb5d7acc2.png)

to this:
![snapshot3](https://cloud.githubusercontent.com/assets/17085857/14144972/edd2ed8a-f689-11e5-881e-6a0761896344.png)

As you know, the meteogram downloaded from yr.no cannot be scaled up without looking terrible. So it's better to render it...

P.S. Personally I prefer the dates in "day/month" format, rather than "day.month." Sorry if this goes against your design goals.

**Comment by kotelnik** [comment]
Thank You for the font fixing! I've made a little adjustments to the meteogram font to be smaller because e.g. the hours were too big. I hope You don't mind.

As for the day/month I've used selfishly czech style with dots. I'll try to use users locale to determine what to show or add a configuration option for that.

**Comment by kotelnik** [comment]
If you still find the font in meteogram too tiny, let me know, I'll make this whole area (along with the font) bigger - this time with hiDPI in mind of course :).

**Comment by tz-m** [comment]
Looks great, thanks!
