### ISSUE TITLE
繁体中文单位翻译错误

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-weather-widget#27]
在54行
`#: ../package/contents/code/unit-utils.js:88`
`#: ../package/contents/ui/config/ConfigUnits.qml:178`
`msgid "km/h"`
`msgstr "公里／秒"`
应该是"公里／时"

**Comment by Wuxiangdong** [comment]
@s8321414

**Comment by Wuxiangdong** [comment]
another issue
@kotelnik 
How to reported issues of transaltion,e-mail or just comment here?
:)

**Comment by FadeMind** [comment]
@Wuxiangdong just create **new issue** or comment here ;)

**Comment by Wuxiangdong** [comment]
Thanks :D @FadeMind

**Comment by s8321414** [comment]
ahh, it should be 公里／小時 or 公里／時, you are right :+1: 
I prefer 公里／小時 though.

**Comment by s8321414** [comment]
@kotelnik can you modify it? I'm lazy to make another PR until new untranslated strings are published :P

**Comment by kotelnik** [comment]
Sure :). Please check this commit https://github.com/kotelnik/plasma-applet-weather-widget/commit/bb85854b3ce0ed80aec63f21c25eb6184e02d9b3

**Comment by s8321414** [comment]
@kotelnik Thanks! I think this issue can be closed now :smiley:

**Comment by s8321414** [comment]
:+1:

**Comment by Wuxiangdong** [comment]
:+1:
