### ISSUE TITLE
Bulgarian translations

### ISSUE THREAD

**Issue by bvbfan** [kotelnik/plasma-applet-weather-widget#32]
I don't want to make fork for one file, it is ok?
[plasma_applet_org.kde.weatherWidget_bg.po.txt](https://github.com/kotelnik/plasma-applet-weather-widget/files/203012/plasma_applet_org.kde.weatherWidget_bg.po.txt)
It's added .txt after, please remove it.

**Comment by kotelnik** [comment]
Cool, thanks for translation! :) I've added your translation in this commit: https://github.com/kotelnik/plasma-applet-weather-widget/commit/4fbe59f52d3981976ce7305898811cf9d0e28c68
And I added your nick and "bg" language in it. I hope you don't mind :).
