### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by mfroeb** [kotelnik/plasma-applet-weather-widget#34]
First of all, thanks for the great work! Works like a charm, very useful.
I attach you the German translation.
[plasma_applet_org.kde.weatherWidget_de.po.txt](https://github.com/kotelnik/plasma-applet-weather-widget/files/333247/plasma_applet_org.kde.weatherWidget_de.po.txt)

**Comment by kotelnik** [comment]
Thank You a lot for Your work! I'll commit it momentarily.
