### ISSUE TITLE
Inclusion in Fedora Repositories

### ISSUE THREAD

**Issue by gbcox** [kotelnik/plasma-applet-weather-widget#38]
Just an FYI for Fedora users:
I've prepared a rpm to include this in Fedora:  [Fedora Review Ticket] (https://bugzilla.redhat.com/show_bug.cgi?id=1367971)
In the meantime, it is available for usage here:  [plasma-applet-weather-widget](https://copr.fedorainfracloud.org/coprs/gbcox/forefront/build/442368/)
I will post an update here when the review process is complete.

**Comment by kotelnik** [comment]
That's a good news! I'm happy that this widget is of any use in Fedora. Thanks for the info :)

**Comment by gbcox** [comment]
Package review and testing completed.  Package has now been pushed from testing to stable for F24.  F25 will follow shortly.
