### ISSUE TITLE
"Encoding" in group "Desktop Entry" is deprecated

### ISSUE THREAD

**Issue by gbcox** [kotelnik/plasma-applet-weather-widget#40]
Noticed this during the build:

builddir/build/BUILDROOT/plasma-applet-weather-widget-1.6.7-4.fc24.x86_64/usr/share/kservices5/plasma-applet-org.kde.weatherWidget.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated

Looks like you should just remove it.
Here is a link:  https://developer.gnome.org/desktop-entry-spec/
It's under C.  Deprecated Items

**Comment by kotelnik** [comment]
Thanks a lot, fixed now.

I also changed custom icon absolute path to a relative one. I hope it doesn't break anything in other systems.
