### ISSUE TITLE
Build Error Fedora - Desktop File Validation Failed

### ISSUE THREAD

**Issue by gbcox** [kotelnik/plasma-applet-weather-widget#44]
Getting this error on the new release:
+ cd /home/gbcox/fedpkg/plasma-applet-weather-widget
+ cd plasma-applet-weather-widget-1.6.8
+ desktop-file-validate /home/gbcox/rpmbuild/BUILDROOT/plasma-applet-weather-widget-1.6.8-1.fc26.x86_64/usr/share/kservices5/plasma-applet-org.kde.weatherWidget.desktop
/home/gbcox/rpmbuild/BUILDROOT/plasma-applet-weather-widget-1.6.8-1.fc26.x86_64/usr/share/kservices5/plasma-applet-org.kde.weatherWidget.desktop: error: value "../plasma/plasmoids/org.kde.weatherWidget/contents/images/weather-widget.svg" for key "Icon" in group "Desktop Entry" looks like a relative path, instead of being an absolute path to an icon or an icon name
error: Bad exit status from /var/tmp/rpm-tmp.7FUmC7 (%check)

Google search brought up quite a few things that may help:
https://www.google.com/search?q=for+key+%22Icon%22+in+group+%22Desktop+Entry%22+looks+like+a+relative+path%2C+instead+of+being+an+absolute+path+to+an+icon+or+an+icon+name&oq=for+key+%22Icon%22+in+group+%22Desktop+Entry%22+looks+like+a+relative+path%2C+instead+of+being+an+absolute+path+to+an+icon+or+an+icon+name&aqs=chrome..69i57j69i64l2.1969j0j9&sourceid=chrome&ie=UTF-8

Better for you to fix it in upstream than me hacking around it..

Thanks!

**Comment by gbcox** [comment]
You can simply change metadata.desktop from:
Icon=../plasma/plasmoids/org.kde.weatherWidget/contents/images/weather-widget.svg
to 
Icon=weather-widget

to fix that error.

I'm now getting:
FAILED:
? tag-invalid           : <icon> not allowed in appdata
? tag-invalid           : stock icon is not valid [weather-widget]

on the validation.  Doing further investigation on that...

**Comment by kotelnik** [comment]
Hi! Thanks for reporting this and guiding me to the specification. I didn't know relative path is not allowed. I reverted the path to the absolute one, that was there before. I know about "Icon=weather-widget" possibility, but in that case the image would need to be installed in common location like /usr/share/icons/breeze/actions/toolbar/. And relative path was the only way to reach the in-plasmoid icon in system wide installation as well as userspace one.

Anyway, reverted. Thanks! And sorry for my late response.

**Comment by gbcox** [comment]
Thanks for the reply.  I'm trying to understand something... perhaps you can help.  You have all your settings in the metadata.desktop file.  During the build two files are created:
org.kde.weatherWidget.appdata.xml
plasma-applet-org.kde.weatherWidget.desktop

Do you know how these are being generated and by what?

The reason I'm asking is that as I mentioned above I'm getting the tag-invalid message on the appdata.xml file.  I've opened a bug on that - not sure whether it's an issue with the validation or with the process that is creating the files.

Thanks!

**Comment by kotelnik** [comment]
I believe these files are generated by extra-cmake-modules, but I suspect You already know that. Unfortunately for now I don't know any more detail about this process.

**Comment by gbcox** [comment]
Thanks for getting back to me on this.... I suspected as much but wanted to double check with you first.  So it appears that in Fedora-land we have a situation where one process is automatically creating files, and another is saying that the files created are invalid.  I know how to work around it, but will try to get it fixed the right way before I resort to hacking around it..

**Comment by gbcox** [comment]
Issue related to invalid icon tag resolved here:  https://bugzilla.redhat.com/show_bug.cgi?id=1411037
I applied the patch to restore the full path you made and that resolved the other issue.  Closing.
