### ISSUE TITLE
version 1.3 doesn't start

### ISSUE THREAD

**Issue by KottV** [kotelnik/plasma-applet-weather-widget#5]
file:///usr/local/share/plasma/plasmoids/org.kde.weatherWidget/contents/ui/main.qml:73:34: Type FullRepresentationInTray unavailable
file:///usr/local/share/plasma/plasmoids/org.kde.weatherWidget/contents/ui/FullRepresentationInTray.qml:21:1: module "QtQuick.Controls" version 1.4 is not installed

opensSUSE 13.2

KF5        :5.12.0

libqt5-qtquickcontrols: 5.4.2

plasma5-desktop    : 5.3.2

**Comment by kotelnik** [comment]
Thanks! Maybe it is connected with Qt 5.5 I have on Arch or something. I downgraded the Controls include to 1.0. Is it working now?

**Comment by KottV** [comment]
Yes, works. Thank You!
