### ISSUE TITLE
plasma applet times out forever after resuming from sleep

### ISSUE THREAD

**Issue by dflogeras** [kotelnik/plasma-applet-weather-widget#52]
Not every time, but once in a while (more often on this laptop that gets opened and closed most frequently) the applet will get stuck updating itself.  The spinner just spins and even toggling "Pause/Resume" updates will not unstick it.  The only way I can find is to logout/login from plasma.  Worst thing (no fault of plasma-applet-weather-widget) is that due to another plasma bug, the spinner consumes a LOT of CPU and runs the battery down much more quickly.

**Comment by kotelnik** [comment]
Thanks for this report. I know about this and I'm currently trying to come up with a fix. It seems it is happening when DNS server is not responding and this is kind of PITA to work around that. I hope I'll make it work.

**Comment by dflogeras** [comment]
Thanks Martin!

**Comment by kotelnik** [comment]
Recently I've finally done more testing. Simulated DNS timeout. By the way - this is how I've done it:
```
# it is advisable to back up the file first
# also make sure that following IP address is not an actual server
echo "nameserver 192.168.0.100" > /etc/resolv.conf
```
I went even in a specific place with wi-fi where I always hit this issue. But I was now unable to replicate that. I'm guessing that Qt 5.9.1 could take care of this issue.

Is this still a problem? Please can you tell me more about your distro, Qt version, etc.? Maybe can you try to replicate with above mentioned test?

**Comment by kotelnik** [comment]
Sorry, I was hit by that issue again yesterday. I'll try to investigate.

**Comment by kotelnik** [comment]
OK, now it should be fixed :). Please reopen if you still see problems.

**Comment by dflogeras** [comment]
Thanks again Martin, I'll request a package bump from Gentoo and then test immediately!
