### ISSUE TITLE
Applet only gets smaller when resized as a desktop applet 

### ISSUE THREAD

**Issue by xenithorb** [kotelnik/plasma-applet-weather-widget#55]
#### Platform:

Applet version: 1.6.9 - `plasma-applet-weather-widget-1.6.9-1.fc26.x86_64`
Plasma version: 5.10.1 - `plasma-workspace-5.10.1-1.fc26.x86_64`
OS: Fedora 26

#### Problem:
 - Applet is unable to be resized properly 

#### Actual result:
 - When trying to resize the applet, it can only be made smaller not larger. 

![weather_widget_resize_issue](https://user-images.githubusercontent.com/10273878/28489845-b725bd28-6e9a-11e7-84fe-ca8a77c84e96.gif)

#### Expected results:
 - Able to arbitrarily resize applet 

#### Notes:
 - First noticed when upgraded from Fedora 25 to Fedora 26 which was a migration to Plasma 5.10.1

**Comment by kotelnik** [comment]
Thanks! I'll fix that.

**Comment by kotelnik** [comment]
I believe it is now fixed in git. Please test and if you encounter problems, reopen. Thanks! :)

**Comment by xenithorb** [comment]
Yes, fixed. Thanks!
