### ISSUE TITLE
Reload the weather make the whole plasma desktop crash.

### ISSUE THREAD

**Issue by trmdi** [kotelnik/plasma-applet-weather-widget#56]
When I click the `Weather Widget` icon on the panel then click the `Reload` button, the whole Plasma desktop crashes. Maybe the CPU is heavily used, I have to restart the computer.

Thank you for this very cool widget.

**Comment by kotelnik** [comment]
Thanks! Is this happening only when you click on the reload button? Does this happen when the widget is reloading automatically? Does this happen witl yr.no provider as well as Open Weather Map?

**Comment by loutr** [comment]
I have the same problem on my computer under Debian Testing.
Informations are still displayed on hover and refreshed, but when I'm clicking on the button it crashes. It does crash only when trying to display graphs for locations chosen with OWM.
This issue randomly appears after booting, but can be "resolved" by changing cities' order in the settings.

**Comment by kotelnik** [comment]
So far I'm quite sure this issue is related to a memory safety problem in XmlListModel component of Qt. I will investigate and possibly file a bug in Qt's Jira as soon as I manage to create a usable minimal example code.

**Comment by kotelnik** [comment]
I may have found a logical problem in my QML code (regarding OpenWeatherMap provider handler) and possibly fixed it. This seems to fix the crashing. I still think it should be fixed in Qt but in any case it should not happen since latest commit. Please reopen this issue if you still encounter this crashing.
